[server]
# Bind to localhost only
address = "0.0.0.0"

# Let Streamlit choose an available port automatically
port = 8501

headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false